<?php

namespace Database\Seeders;

use App\Models\BankAccount;
use App\Models\Branch;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BankAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Make sure we have at least one branch
        $branch = Branch::first();
        if (!$branch) {
            $branch = Branch::create([
                'name' => 'Main Branch',
                'code' => 'MAIN',
                'address' => 'Addis Ababa, Ethiopia',
                'phone' => '+251-111-222-333',
                'email' => 'main@stock360.com',
                'is_active' => true,
            ]);
        }

        // Create bank accounts
        $accounts = [
            [
                'account_name' => 'Cash Drawer',
                'account_number' => 'CASH-001',
                'bank_name' => 'Cash Drawer',
                'branch_name' => 'Main Office',
                'balance' => 50000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => true,
                'branch_id' => $branch->id,
                'notes' => 'Virtual cash drawer for cash transactions',
            ],
            [
                'account_name' => 'Commercial Bank of Ethiopia - Main',
                'account_number' => '1000123456789',
                'bank_name' => 'Commercial Bank of Ethiopia',
                'branch_name' => 'Bole Branch',
                'swift_code' => 'CBETETAA',
                'balance' => 100000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Main business account',
            ],
            [
                'account_name' => 'Dashen Bank - Business',
                'account_number' => '2000123456789',
                'bank_name' => 'Dashen Bank',
                'branch_name' => 'Addis Ababa',
                'swift_code' => 'DASHETAA',
                'balance' => 75000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Secondary business account',
            ],
            [
                'account_name' => 'Abyssinia Bank - Trading',
                'account_number' => '3000123456789',
                'bank_name' => 'Abyssinia Bank',
                'branch_name' => 'Merkato Branch',
                'swift_code' => 'ABYSETAA',
                'balance' => 60000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Abyssinia Bank business account',
            ],
            [
                'account_name' => 'Bank of Abyssinia - Current',
                'account_number' => '4000123456789',
                'bank_name' => 'Bank of Abyssinia',
                'branch_name' => 'Piazza Branch',
                'swift_code' => 'BOAEETAA',
                'balance' => 45000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Bank of Abyssinia account',
            ],
            [
                'account_name' => 'Awash Bank - Operations',
                'account_number' => '5000123456789',
                'bank_name' => 'Awash Bank',
                'branch_name' => 'Arat Kilo Branch',
                'swift_code' => 'AWSHETAA',
                'balance' => 80000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Awash Bank business account',
            ],
            [
                'account_name' => 'United Bank - General',
                'account_number' => '6000123456789',
                'bank_name' => 'United Bank',
                'branch_name' => 'Mexico Branch',
                'swift_code' => 'UNTDETAA',
                'balance' => 55000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'United Bank account',
            ],
            [
                'account_name' => 'Wegagen Bank - Business',
                'account_number' => '7000123456789',
                'bank_name' => 'Wegagen Bank',
                'branch_name' => 'Bole Branch',
                'swift_code' => 'WEGAETAA',
                'balance' => 65000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Wegagen Bank business account',
            ],
            [
                'account_name' => 'Nib International Bank - Trading',
                'account_number' => '8000123456789',
                'bank_name' => 'Nib International Bank',
                'branch_name' => 'Kazanchis Branch',
                'swift_code' => 'NIIBETAA',
                'balance' => 70000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Nib International Bank account',
            ],
            [
                'account_name' => 'Cooperative Bank of Oromia - Main',
                'account_number' => '9000123456789',
                'bank_name' => 'Cooperative Bank of Oromia',
                'branch_name' => 'Adama Branch',
                'swift_code' => 'CBORETAA',
                'balance' => 40000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Cooperative Bank of Oromia account',
            ],
            [
                'account_name' => 'Lion International Bank - Business',
                'account_number' => '1100123456789',
                'bank_name' => 'Lion International Bank',
                'branch_name' => 'Megenagna Branch',
                'swift_code' => 'LIBSETAA',
                'balance' => 85000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Lion International Bank account',
            ],
            [
                'account_name' => 'Zemen Bank - Corporate',
                'account_number' => '1200123456789',
                'bank_name' => 'Zemen Bank',
                'branch_name' => 'Sarbet Branch',
                'swift_code' => 'ZEMENAA',
                'balance' => 90000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Zemen Bank corporate account',
            ],
            [
                'account_name' => 'Bunna International Bank - Main',
                'account_number' => '1300123456789',
                'bank_name' => 'Bunna International Bank',
                'branch_name' => 'Gotera Branch',
                'swift_code' => 'BUNAETAA',
                'balance' => 50000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Bunna International Bank account',
            ],
            [
                'account_name' => 'Berhan International Bank - Trading',
                'account_number' => '1400123456789',
                'bank_name' => 'Berhan International Bank',
                'branch_name' => 'Hayahulet Branch',
                'swift_code' => 'BIIBETAA',
                'balance' => 72000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Berhan International Bank account',
            ],
            [
                'account_name' => 'Addis International Bank - Business',
                'account_number' => '1500123456789',
                'bank_name' => 'Addis International Bank',
                'branch_name' => 'CMC Branch',
                'swift_code' => 'AIBKETAA',
                'balance' => 68000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Addis International Bank account',
            ],
            [
                'account_name' => 'Oromia International Bank - Main',
                'account_number' => '1600123456789',
                'bank_name' => 'Oromia International Bank',
                'branch_name' => 'Bole Branch',
                'swift_code' => 'OIBSETAA',
                'balance' => 95000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Oromia International Bank account',
            ],
            [
                'account_name' => 'Debub Global Bank - Corporate',
                'account_number' => '1700123456789',
                'bank_name' => 'Debub Global Bank',
                'branch_name' => 'Hawassa Branch',
                'swift_code' => 'DGBSETAA',
                'balance' => 58000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Debub Global Bank account',
            ],
            [
                'account_name' => 'Enat Bank - Business',
                'account_number' => '1800123456789',
                'bank_name' => 'Enat Bank',
                'branch_name' => 'Gerji Branch',
                'swift_code' => 'ENATBAA',
                'balance' => 62000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Enat Bank business account',
            ],
            [
                'account_name' => 'Siinqee Bank - Trading',
                'account_number' => '1900123456789',
                'bank_name' => 'Siinqee Bank',
                'branch_name' => 'Jimma Branch',
                'swift_code' => 'SIIQETAA',
                'balance' => 48000,
                'currency' => 'ETB',
                'is_active' => true,
                'is_default' => false,
                'branch_id' => $branch->id,
                'notes' => 'Siinqee Bank trading account',
            ],
        ];

        foreach ($accounts as $account) {
            // Only create if it doesn't already exist
            if (!BankAccount::where('account_number', $account['account_number'])->exists()) {
                BankAccount::create($account);
            }
        }
    }
}
