services:
    php:
        build: .
        container_name: amtradingplc-php
        working_dir: /app
        volumes:
            - .:/app
            - vendor:/app/vendor
            - node_modules:/app/node_modules
        ports:
            - "8000:8000"
        depends_on:
            node:
                condition: service_started
            db:
                condition: service_healthy
        environment:
            - DB_HOST=db
            - DB_DATABASE=amtradingplc
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - APP_ENV=local
            - APP_DEBUG=true
            - COMPOSER_PROCESS_TIMEOUT=1200
            - COMPOSER_MEMORY_LIMIT=-1
            - COMPOSER_ALLOW_SUPERUSER=1
        command: >
            bash docker/php/entrypoint.sh
        restart: unless-stopped

    node:
        image: node:18-alpine
        container_name: amtradingplc-node
        working_dir: /app
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - "5173:5173"
        environment:
            - APP_ENV=${APP_ENV:-local}
        command: >
            sh -c "(npm ci --no-audit --no-fund || npm install --no-audit --no-fund) && npm run dev -- --host 0.0.0.0 --port 5173 --config vite.config.mjs"
        restart: unless-stopped

    db:
        image: mysql:8.0
        container_name: amtradingplc-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: amtradingplc
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/dev.cnf:ro
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        command:
            - mysqld
            - --defaults-file=/etc/mysql/conf.d/dev.cnf

volumes:
    db_data:
    vendor:
    node_modules:
