<?php

declare(strict_types=1);

namespace App\Support\Access;

use App\Enums\UserRole;

final class PermissionCatalog
{
    /**
     * @return array<int, string>
     */
    public static function permissions(): array
    {
        return [
            'activities.view',
            'bank-accounts.view',
            'bank-accounts.create',
            'bank-accounts.edit',
            'bank-accounts.delete',
            'branches.view',
            'branches.create',
            'branches.edit',
            'branches.delete',
            'categories.view',
            'categories.create',
            'categories.edit',
            'categories.delete',
            'credits.view',
            'credits.create',
            'credits.edit',
            'credits.delete',
            'customers.view',
            'customers.create',
            'customers.edit',
            'customers.delete',
            'employees.view',
            'employees.create',
            'employees.edit',
            'employees.delete',
            'expenses.view',
            'expenses.create',
            'expenses.edit',
            'expenses.delete',
            'items.view',
            'items.create',
            'items.edit',
            'items.delete',
            'payments.view',
            'payments.create',
            'purchases.view',
            'purchases.create',
            'purchases.edit',
            'purchases.delete',
            'purchases.approve',
            'purchases.receive',
            'reports.view',
            'reports.export',
            'returns.view',
            'returns.create',
            'returns.edit',
            'returns.delete',
            'returns.approve',
            'roles.view',
            'roles.create',
            'roles.edit',
            'roles.delete',
            'sales.view',
            'sales.create',
            'sales.edit',
            'sales.delete',
            'settings.manage',
            'stock.view',
            'stock.adjust',
            'stock.history',
            'stock-card.view',
            'stock-card.create',
            'suppliers.view',
            'suppliers.create',
            'suppliers.edit',
            'suppliers.delete',
            'transfers.view',
            'transfers.create',
            'transfers.edit',
            'transfers.delete',
            'transfers.approve',
            'transfers.receive',
            'users.view',
            'users.create',
            'users.edit',
            'users.delete',
            'warehouses.view',
            'warehouses.create',
            'warehouses.edit',
            'warehouses.delete',
        ];
    }

    /**
     * @return array<string, array<int, string>>
     */
    public static function rolePermissions(): array
    {
        return [
            UserRole::SUPER_ADMIN->value => self::permissions(),
            UserRole::GENERAL_MANAGER->value => self::permissions(),
            UserRole::BRANCH_MANAGER->value => [
                'activities.view',
                'bank-accounts.view',
                'branches.view',
                'categories.view',
                'categories.create',
                'categories.edit',
                'credits.view',
                'credits.create',
                'credits.edit',
                'customers.view',
                'customers.create',
                'customers.edit',
                'employees.view',
                'employees.create',
                'employees.edit',
                'expenses.view',
                'expenses.create',
                'expenses.edit',
                'items.view',
                'items.create',
                'items.edit',
                'purchases.view',
                'purchases.create',
                'purchases.approve',
                'purchases.receive',
                'reports.view',
                'sales.view',
                'sales.create',
                'sales.edit',
                'stock.view',
                'stock.history',
                'stock-card.view',
                'stock-card.create',
                'suppliers.view',
                'suppliers.create',
                'suppliers.edit',
                'transfers.view',
                'transfers.create',
                'transfers.edit',
                'transfers.delete',
                'transfers.approve',
                'transfers.receive',
                'users.view',
                'warehouses.view',
            ],
            UserRole::WAREHOUSE_MANAGER->value => [
                'activities.view',
                'categories.view',
                'items.view',
                'items.edit',
                'stock.view',
                'stock.adjust',
                'stock.history',
                'stock-card.view',
                'stock-card.create',
                'transfers.view',
                'transfers.create',
                'transfers.edit',
                'transfers.receive',
                'warehouses.view',
            ],
            UserRole::ACCOUNTANT->value => [
                'bank-accounts.view',
                'bank-accounts.create',
                'bank-accounts.edit',
                'credits.view',
                'credits.edit',
                'expenses.view',
                'expenses.create',
                'expenses.edit',
                'items.view',
                'purchases.view',
                'reports.view',
                'reports.export',
                'sales.view',
                'stock.view',
                'stock-card.view',
            ],
            UserRole::CUSTOMER_SERVICE->value => [
                'customers.view',
                'customers.create',
                'customers.edit',
                'sales.view',
                'sales.create',
            ],
            UserRole::SALES->value => [
                'activities.view',
                'categories.view',
                'customers.view',
                'customers.create',
                'customers.edit',
                'items.view',
                'purchases.view',
                'sales.view',
                'sales.create',
                'stock.view',
            ],
            UserRole::PURCHASE_OFFICER->value => [
                'categories.view',
                'items.view',
                'items.create',
                'items.edit',
                'purchases.view',
                'purchases.create',
                'stock.view',
                'suppliers.view',
                'suppliers.create',
                'suppliers.edit',
            ],
        ];
    }
}
